name: ESLint

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main # Or your default branch

jobs:
  eslint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x] # Or your desired Node.js version(s)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Or 'yarn' or 'pnpm'

      - name: Install dependencies
        run: npm ci # Or yarn install or pnpm install

      - name: Run ESLint
        run: npm run lint # Or npx eslint .